-- Kör dessa SQL-kommandon i Supabase SQL Editor för att uppgradera databasen
-- (Radera din gamla `meny`-tabell manuellt i Supabase-gränssnittet om du vill städa)

-- 1. Tabell för Menyer (t.ex. Lunch, Middag)
CREATE TABLE menyer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namn TEXT NOT NULL,
  beskrivning TEXT,
  aktiv BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabell för Maträtter
CREATE TABLE ratter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meny_id BIGINT REFERENCES menyer(id) ON DELETE CASCADE,
  namn TEXT NOT NULL,
  beskrivning TEXT,
  baspris NUMERIC NOT NULL,
  kategori TEXT NOT NULL,
  aktiv BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabell för Tillvalsgrupper (t.ex. "Välj protein", "Extra tillbehör")
CREATE TABLE tillvals_grupper (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namn TEXT NOT NULL,
  obligatorisk BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabell för Tillvalsalternativ (t.ex. "Kyckling +0kr", "Biff +20kr")
CREATE TABLE tillvals_alternativ (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupp_id BIGINT REFERENCES tillvals_grupper(id) ON DELETE CASCADE,
  namn TEXT NOT NULL,
  extra_pris NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Kopplingstabell (Many-to-Many) mellan rätter och tillvalsgrupper
CREATE TABLE ratt_tillval (
  ratt_id BIGINT REFERENCES ratter(id) ON DELETE CASCADE,
  grupp_id BIGINT REFERENCES tillvals_grupper(id) ON DELETE CASCADE,
  PRIMARY KEY (ratt_id, grupp_id)
);

-- ==== ROW LEVEL SECURITY (RLS) ====

ALTER TABLE menyer ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratter ENABLE ROW LEVEL SECURITY;
ALTER TABLE tillvals_grupper ENABLE ROW LEVEL SECURITY;
ALTER TABLE tillvals_alternativ ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratt_tillval ENABLE ROW LEVEL SECURITY;

-- Alla (även besökare) kan läsa menysystemet
CREATE POLICY "Alla kan läsa menyer" ON menyer FOR SELECT USING (true);
CREATE POLICY "Alla kan läsa ratter" ON ratter FOR SELECT USING (true);
CREATE POLICY "Alla kan läsa tillvals_grupper" ON tillvals_grupper FOR SELECT USING (true);
CREATE POLICY "Alla kan läsa tillvals_alternativ" ON tillvals_alternativ FOR SELECT USING (true);
CREATE POLICY "Alla kan läsa ratt_tillval" ON ratt_tillval FOR SELECT USING (true);

-- Endast admins kan ändra
CREATE POLICY "Admins hanterar menyer" ON menyer FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins hanterar ratter" ON ratter FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins hanterar tillvals_grupper" ON tillvals_grupper FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins hanterar tillvals_alternativ" ON tillvals_alternativ FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins hanterar ratt_tillval" ON ratt_tillval FOR ALL USING (auth.role() = 'authenticated');
