-- Kör dessa SQL-kommandon i Supabase SQL Editor

-- 1. Tabell för Meny
CREATE TABLE meny (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namn TEXT NOT NULL,
  beskrivning TEXT,
  pris NUMERIC NOT NULL,
  kategori TEXT NOT NULL,
  aktiv BOOLEAN DEFAULT TRUE
);

-- 2. Tabell för Bokningar
CREATE TABLE bokningar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namn TEXT NOT NULL,
  telefon TEXT NOT NULL,
  epost TEXT NOT NULL,
  datum TIMESTAMP WITH TIME ZONE NOT NULL,
  antal INTEGER NOT NULL,
  status TEXT DEFAULT 'Bekräftad',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabell för Ordrar
CREATE TABLE ordrar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kundnamn TEXT NOT NULL,
  epost TEXT NOT NULL,
  hamtningstid TIMESTAMP WITH TIME ZONE NOT NULL,
  total_belopp NUMERIC NOT NULL,
  betald BOOLEAN DEFAULT FALSE,
  paypal_order_id TEXT,
  status TEXT DEFAULT 'Betald',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ratter JSONB -- Sparar arrayen med maträtter
);

-- Slå på RLS på alla tabeller
ALTER TABLE meny ENABLE ROW LEVEL SECURITY;
ALTER TABLE bokningar ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordrar ENABLE ROW LEVEL SECURITY;

-- ===== RLS POLICIES =====

-- MENY Policies
-- Vem som helst kan läsa menyn
CREATE POLICY "Alla kan läsa menyn" ON meny FOR SELECT USING (true);
-- Endast inloggade administratörer kan ändra menyn
CREATE POLICY "Admins kan hantera menyn" ON meny FOR ALL USING (auth.role() = 'authenticated');

-- BOKNINGAR Policies
-- Vem som helst (anonym) kan lägga till en bokning
CREATE POLICY "Alla kan boka bord" ON bokningar FOR INSERT WITH CHECK (true);
-- Endast inloggade administratörer kan läsa/ändra alla bokningar
CREATE POLICY "Admins hanterar bokningar" ON bokningar FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins uppdaterar bokningar" ON bokningar FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins raderar bokningar" ON bokningar FOR DELETE USING (auth.role() = 'authenticated');

-- ORDRAR Policies
-- Vem som helst kan skapa en order
CREATE POLICY "Alla kan skapa ordrar" ON ordrar FOR INSERT WITH CHECK (true);
-- Endast inloggade administratörer kan läsa/ändra ordrar
CREATE POLICY "Admins hanterar ordrar" ON ordrar FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins uppdaterar ordrar" ON ordrar FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins raderar ordrar" ON ordrar FOR DELETE USING (auth.role() = 'authenticated');

-- TIPS: För att få realtidsuppdateringar på frontend (admin panel) måste vi slå på replikering:
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table ordrar, bokningar;

-- 4. Tabell för Inställningar (t.ex. PayPal Client ID)
CREATE TABLE installningar (
  nyckel TEXT PRIMARY KEY,
  varde TEXT NOT NULL
);

ALTER TABLE installningar ENABLE ROW LEVEL SECURITY;

-- Alla kan läsa inställningar (så frontenden kan hämta PayPal ID)
CREATE POLICY "Alla kan läsa inställningar" ON installningar FOR SELECT USING (true);
-- Endast admins kan uppdatera/lägga till
CREATE POLICY "Admins hanterar inställningar" ON installningar FOR ALL USING (auth.role() = 'authenticated');
